// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Web_Api_Learning
{
    public partial class MumbaiIndians
    {
        public int id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public int isCaptain { get; set; }
        public string BattingStyle { get; set; }
        public int isKeeper { get; set; }
        public int isAllRounder { get; set; }
        public string BowlingStyle { get; set; }
    }
}