// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Web_Api_Learning
{
    public partial class PLAYERS
    {
        public int id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Nationality { get; set; }
        public string IplTeam { get; set; }
        public long? Runs { get; set; }
        public double? Average { get; set; }
        public int? Centuries { get; set; }
        public int? Fifties { get; set; }
        public int? Fours { get; set; }
        public int? Sixes { get; set; }
        public double? StrikeRate { get; set; }
        public int? Wickets { get; set; }
        public double? Economy { get; set; }
        public double? BAverage { get; set; }
        public int? Fifers { get; set; }
    }
}