// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Web_Api_Learning
{
    public partial class TEAMS
    {
        public int id { get; set; }
        public string TeamName { get; set; }
    }
}